"""tabel makanan

Revision ID: 8bd641b4aedb
Revises: 
Create Date: 2021-05-08 08:56:57.376816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd641b4aedb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('makanan',
    sa.Column('id_makanan', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_makanan', sa.String(length=50), nullable=False),
    sa.Column('kalori_makanan', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_makanan')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('makanan')
    # ### end Alembic commands ###
